project:
  type: book
  output-dir: docs

book:
  title: "Modeling Choice and RT"
  author: "Gregory E. Cox"
  date: "1/12/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - history.qmd
    - random_walk.qmd
    - diffusion_sim.qmd
    - diffusion_fit.qmd
    - blast_example.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    code-fold: true

editor: source